name: Create Ruleset

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  # Get the current step from .github/script/STEP so we can
  # limit running the main job when the learner is on the same step.
  prevent-direct-commits:
    name: Lock master branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: actions/setup-gh@v2

      - name: Restrict master branch
        run: |
          echo "Restrict master branch"
          repositoryId="$(gh api graphql -f query='{repository(${{ github.repository }}){id}}' -q .data.repository.id)"
          gh api graphql -f query='mutation($repositoryId:ID!,$branch:String!) {
            createBranchProtectionRule(input: {
            repositoryId: $repositoryId
            pattern: $branch
            allowsDeletions: false
            allowsForcePushes: false
            requiredApprovingReviewCount: 1
            requiresStatusChecks: true
            requiresStrictStatusChecks: true
            restrictsPushes: true
            lockBranch: true
            }) { clientMutationId } }' -f repositoryId="$repositoryId" -f branch=master
