name: Create Ruleset

on:
  workflow_dispatch:
  push:
    branches:
      - main

# Reference https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to update the step metadata
  # Need `pull-requests: write` to create a pull request
  contents: write
  pull-requests: write

jobs:
  # Get the current step from .github/script/STEP so we can
  # limit running the main job when the learner is on the same step.
  prevent-direct-commits:
    name: Check current step number
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README
      - name: Checkout
        uses: actions/checkout@v3

      # Make a branch, file, commit, and pull request for the learner
      - name: Restrict master branch
        run: |
          echo "Restrict master branch"
          repositoryId="$(gh api graphql -f query='{repository(owner:\"owner\",name:\"repo\"){id}}' -q .data.repository.id)"
          gh api graphql -f query='mutation($repositoryId:ID!,$branch:String!) {
            createBranchProtectionRule(input: {
            repositoryId: $repositoryId
            pattern: $branch
            allowsDeletions: false
            allowsForcePushes: false
            requiredApprovingReviewCount: 1
            requiresStatusChecks: true
            requiresStrictStatusChecks: true
            restrictsPushes: true
            lockBranch: true
            }) { clientMutationId } }' -f repositoryId="$repositoryId" -f branch=master
