name: Create Ruleset

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  prevent-direct-commits:
    name: Lock master branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Restrict master branch
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Restrict master branch"
          repositoryId="$(gh api graphql -f query='query { repository(owner: "${{ github.repository_owner }}", name: "${{ github.event.repository.name }}") { id } }' -q .data.repository.id)"
          gh api graphql -f query='mutation($repositoryId:ID!,$branch:String!) {
            createBranchProtectionRule(input: {
              repositoryId: $repositoryId
              pattern: $branch
              allowsDeletions: false
              allowsForcePushes: false
              requiredApprovingReviewCount: 1
              requiresStatusChecks: true
              requiresStrictStatusChecks: true
              restrictsPushes: true
              lockBranch: true
            }) { clientMutationId } }' -f repositoryId="$repositoryId" -f branch=master
